### ISSUE TITLE
CORB on contributors icons. 

### ISSUE THREAD

**Issue by O5ten** [RoadieHQ/backstage-plugin-github-insights#20]
I'm getting CORB when opening the insights page. Is this something i need to configure locally, or in my GHE instance? 
I can properly inspect the contributor and find links to GHE depicting the person. But the image is missing. 

**Version:** 
"@roadiehq/backstage-plugin-github-insights": "^0.2.15"

**Chrome Error Message**
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://ghe.************.com/login?return_to=https%3A%2F%2Fghe..************.com%2FMikael-Ostberg.png with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Related app-config.yaml**
```
  cors:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", "data:", "https://ghe.****************.com"]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
```
