### ISSUE TITLE
Bad Credentials error when used with GitHub Enterprise

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage-plugin-github-insights#6]
From Discord ([link to message](https://discord.com/channels/687207715902193673/687235481154617364/770488208320495636)):

> GHE instances have two formats: https://api.host.com/ or https://host.com/api/v3. My firm uses the latter.  I've played around with lots of permutations of host, base URL, etc, and no matter what the GitHub Insights plugin just always shows Bad Credentials but I can't seem to trigger any additional debugging to find out why. (even w/ LOG_LEVEL=debug as env var)   GHE interface says my PAT has been used, but that may only be because it works in integrations for loading up catalog YAMLs.  Welcome any, achem, insights!

```
catalog:
  processors:
    githubOrg:
      providers:
        - target: https://myhost.mycompany.com
          apiBaseUrl: https://myhost.mycompany.com/api/v3
          token: myPATtoken
scaffolder:
  github:
    host: https://myhost.mycompany.com/api/v3
    token: myPATtoken
    visibility: public
```

![bad-creds](https://user-images.githubusercontent.com/562403/97280859-b6d96a80-1834-11eb-8d6d-5e1d651c1c4d.png)
